In [1]:
import pandas as pd

In [2]:
#建立文本数据
documents=[['菜品','很','一般','不','建议','在这','消费'],
          ['老板','很','闹心','坑人','建议','去','别家'],
          ['让人','惊艳','东西','口味','让人','感觉','不错'],
          ['环境','不错','自然牛柳','很','好吃'],
          ['味道','真的','一般般','环境','也','比较','拥挤'],
          ['一家','性价比','很','高','餐厅','推荐']]

In [3]:
classVec=[1,1,0,0,1,0]

In [4]:
words_all=set() #建立字典

In [5]:
#创建词集合
for document in documents:
    words_all=words_all|set(document) #并运算，并且没有重复

In [6]:
words_all

{'一家',
 '一般',
 '一般般',
 '不',
 '不错',
 '东西',
 '也',
 '别家',
 '去',
 '口味',
 '味道',
 '在这',
 '坑人',
 '好吃',
 '建议',
 '很',
 '性价比',
 '惊艳',
 '感觉',
 '拥挤',
 '推荐',
 '比较',
 '消费',
 '环境',
 '真的',
 '老板',
 '自然牛柳',
 '菜品',
 '让人',
 '闹心',
 '餐厅',
 '高'}

In [7]:
#将词集合转化为列表
words_all=list(words_all)

In [8]:
words_all

['在这',
 '闹心',
 '建议',
 '东西',
 '一般般',
 '自然牛柳',
 '也',
 '让人',
 '真的',
 '一家',
 '菜品',
 '去',
 '消费',
 '坑人',
 '一般',
 '味道',
 '感觉',
 '好吃',
 '不错',
 '餐厅',
 '推荐',
 '比较',
 '别家',
 '拥挤',
 '惊艳',
 '环境',
 '高',
 '口味',
 '不',
 '很',
 '老板',
 '性价比']

In [9]:
dic={}

In [10]:
document=documents[0]

In [11]:
for word in words_all

SyntaxError: expected ':' (1892894169.py, line 1)

In [12]:
def creat_wordVec(document,words_all):
    dic={}
    for word in words_all:
        if word in document:
            dic[word]=1
        else:
            dic[word]=0
    return dic

In [13]:
trainMatrix=[]

In [14]:
for document in documents:
    trainMatrix.append(creat_wordVec(document,words_all))

In [15]:
trainMatrix

[{'在这': 1,
  '闹心': 0,
  '建议': 1,
  '东西': 0,
  '一般般': 0,
  '自然牛柳': 0,
  '也': 0,
  '让人': 0,
  '真的': 0,
  '一家': 0,
  '菜品': 1,
  '去': 0,
  '消费': 1,
  '坑人': 0,
  '一般': 1,
  '味道': 0,
  '感觉': 0,
  '好吃': 0,
  '不错': 0,
  '餐厅': 0,
  '推荐': 0,
  '比较': 0,
  '别家': 0,
  '拥挤': 0,
  '惊艳': 0,
  '环境': 0,
  '高': 0,
  '口味': 0,
  '不': 1,
  '很': 1,
  '老板': 0,
  '性价比': 0},
 {'在这': 0,
  '闹心': 1,
  '建议': 1,
  '东西': 0,
  '一般般': 0,
  '自然牛柳': 0,
  '也': 0,
  '让人': 0,
  '真的': 0,
  '一家': 0,
  '菜品': 0,
  '去': 1,
  '消费': 0,
  '坑人': 1,
  '一般': 0,
  '味道': 0,
  '感觉': 0,
  '好吃': 0,
  '不错': 0,
  '餐厅': 0,
  '推荐': 0,
  '比较': 0,
  '别家': 1,
  '拥挤': 0,
  '惊艳': 0,
  '环境': 0,
  '高': 0,
  '口味': 0,
  '不': 0,
  '很': 1,
  '老板': 1,
  '性价比': 0},
 {'在这': 0,
  '闹心': 0,
  '建议': 0,
  '东西': 1,
  '一般般': 0,
  '自然牛柳': 0,
  '也': 0,
  '让人': 1,
  '真的': 0,
  '一家': 0,
  '菜品': 0,
  '去': 0,
  '消费': 0,
  '坑人': 0,
  '一般': 0,
  '味道': 0,
  '感觉': 1,
  '好吃': 0,
  '不错': 1,
  '餐厅': 0,
  '推荐': 0,
  '比较': 0,
  '别家': 0,
  '拥挤': 0,
  '惊艳': 1,
  '环境': 0,
  '高': 0,
  '口味': 1,
  '不': 0,
  '很': 0,
  '老板': 0,
  '性价比': 0},
 {'在这': 0,
  '闹心': 0,
  '建议': 0,
  '东西': 0,
  '一般般': 0,
  '自然牛柳': 1,
  '也': 0,
  '让人': 0,
  '真的': 0,
  '一家': 0,
  '菜品': 0,
  '去': 0,
  '消费': 0,
  '坑人': 0,
  '一般': 0,
  '味道': 0,
  '感觉': 0,
  '好吃': 1,
  '不错': 1,
  '餐厅': 0,
  '推荐': 0,
  '比较': 0,
  '别家': 0,
  '拥挤': 0,
  '惊艳': 0,
  '环境': 1,
  '高': 0,
  '口味': 0,
  '不': 0,
  '很': 1,
  '老板': 0,
  '性价比': 0},
 {'在这': 0,
  '闹心': 0,
  '建议': 0,
  '东西': 0,
  '一般般': 1,
  '自然牛柳': 0,
  '也': 1,
  '让人': 0,
  '真的': 1,
  '一家': 0,
  '菜品': 0,
  '去': 0,
  '消费': 0,
  '坑人': 0,
  '一般': 0,
  '味道': 1,
  '感觉': 0,
  '好吃': 0,
  '不错': 0,
  '餐厅': 0,
  '推荐': 0,
  '比较': 1,
  '别家': 0,
  '拥挤': 1,
  '惊艳': 0,
  '环境': 1,
  '高': 0,
  '口味': 0,
  '不': 0,
  '很': 0,
  '老板': 0,
  '性价比': 0},
 {'在这': 0,
  '闹心': 0,
  '建议': 0,
  '东西': 0,
  '一般般': 0,
  '自然牛柳': 0,
  '也': 0,
  '让人': 0,
  '真的': 0,
  '一家': 1,
  '菜品': 0,
  '去': 0,
  '消费': 0,
  '坑人': 0,
  '一般': 0,
  '味道': 0,
  '感觉': 0,
  '好吃': 0,
  '不错': 0,
  '餐厅': 1,
  '推荐': 1,
  '比较': 0,
  '别家': 0,
  '拥挤': 0,
  '惊艳': 0,
  '环境': 0,
  '高': 1,
  '口味': 0,
  '不': 0,
  '很': 1,
  '老板': 0,
  '性价比': 1}]

In [16]:
df=pd.DataFrame(trainMatrix)

In [17]:
df

,在这,闹心,建议,东西,一般般,自然牛柳,也,让人,真的,一家,...,别家,拥挤,惊艳,环境,高,口味,不,很,老板,性价比
0,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,0,0
1,0,1,1,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,1,1,0
2,0,0,0,1,0,0,0,1,0,0,...,0,0,1,0,0,1,0,0,0,0
3,0,0,0,0,0,1,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
4,0,0,0,0,1,0,1,0,1,0,...,0,1,0,1,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,1,0,0,1,0,1

In [19]:
#将标签转换为序列
se=pd.Series(classVec)
#取消极词的数据
df_neg=df[se==1]

In [20]:
se

0    1
1    1
2    0
3    0
4    1
5    0
dtype: int64

In [25]:
df_neg

,口味,高,惊艳,一般般,建议,环境,味道,推荐,坑人,别家,...,餐厅,很,感觉,一般,消费,不,老板,不错,一家,性价比
0,0,0,0,0,1,0,0,0,0,0,...,0,1,0,1,1,1,0,0,0,0
1,0,0,0,0,1,0,0,0,1,1,...,0,1,0,0,0,0,1,0,0,0
4,0,0,0,1,0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [28]:
#词出现的次数
p_negWordNum=df_neg.sum(axis=0)
p_negWordNum

口味      0
高       0
惊艳      0
一般般     1
建议      2
环境      1
味道      1
推荐      0
坑人      1
别家      1
闹心      1
菜品      1
拥挤      1
在这      1
比较      1
也       1
好吃      0
去       1
自然牛柳    0
让人      0
真的      1
东西      0
餐厅      0
很       2
感觉      0
一般      1
消费      1
不       1
老板      1
不错      0
一家      0
性价比     0
dtype: int64

In [29]:
#消极词的总数
p_negAllNmum=p_negWordNum.sum()
p_negAllNmum

21

In [30]:
#消极词的条件概率
p_negVect=p_negWordNum/p_negAllNmum
p_negVect

口味      0.000000
高       0.000000
惊艳      0.000000
一般般     0.047619
建议      0.095238
环境      0.047619
味道      0.047619
推荐      0.000000
坑人      0.047619
别家      0.047619
闹心      0.047619
菜品      0.047619
拥挤      0.047619
在这      0.047619
比较      0.047619
也       0.047619
好吃      0.000000
去       0.047619
自然牛柳    0.000000
让人      0.000000
真的      0.047619
东西      0.000000
餐厅      0.000000
很       0.095238
感觉      0.000000
一般      0.047619
消费      0.047619
不       0.047619
老板      0.047619
不错      0.000000
一家      0.000000
性价比     0.000000
dtype: float64

In [31]:
p_negDoc=len(df_neg)/len(df)
p_negDoc

0.5

In [33]:
df_pos=df[se==0]
p_posWordNum=df_pos.sum(axis=0)
p_posAllNmum=p_posWordNum.sum()
p_posVect=p_posWordNum/p_posAllNmum
p_posDoc=len(df_pos)/len(df)

In [35]:
print(p_posVect)
print(p_posDoc)

口味      0.058824
高       0.058824
惊艳      0.058824
一般般     0.000000
建议      0.000000
环境      0.058824
味道      0.000000
推荐      0.058824
坑人      0.000000
别家      0.000000
闹心      0.000000
菜品      0.000000
拥挤      0.000000
在这      0.000000
比较      0.000000
也       0.000000
好吃      0.058824
去       0.000000
自然牛柳    0.058824
让人      0.058824
真的      0.000000
东西      0.058824
餐厅      0.058824
很       0.117647
感觉      0.058824
一般      0.000000
消费      0.000000
不       0.000000
老板      0.000000
不错      0.117647
一家      0.058824
性价比     0.058824
dtype: float64
0.5

In [36]:
testDoc=['环境','很','不错']

In [38]:
p_negCurVect=p_negVect[testDoc]
p_negCurVect

环境    0.047619
很     0.095238
不错    0.000000
dtype: float64

In [44]:
p_negCla=p_negDoc

In [40]:
#计算总概率
p_negFeatCla=p_negCurVect.prod()
p_negFeatCla

0.0

In [41]:
p_posCurVect=p_posVect[testDoc]
p_posCurVect

环境    0.058824
很     0.117647
不错    0.117647
dtype: float64

In [42]:
p_posFeatCla=p_posCurVect.prod()
p_posFeatCla

0.0008141664970486464

In [45]:
p_posCla=1-p_negCla

In [46]:
p_posFeatCla=p_posFeatCla*p_posCla

In [47]:
p_posFeatCla

0.0004070832485243232

In [49]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

In [51]:
wines=datasets.load_wine()
X=wines['data']
y=wines['target']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)
gnb=GaussianNB()

In [52]:
gnb.fit(X_train,y_train)

GaussianNB()

In [54]:
gnb.score(X_test,y_test)

0.9444444444444444

In [59]:
diabetes=datasets.load_diabetes()
X=diabetes['data']
y=diabetes['target']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)
gnb=GaussianNB()

In [60]:
gnb.fit(X_train,y_train)

GaussianNB()

In [62]:
y_test

array([341.,  72.,  63.,  79., 164., 118., 197., 168.,  97.,  51.,  74.,
       110., 146., 147., 202., 214., 216., 263., 321., 225.,  53.,  50.,
        43.,  64., 101.,  73., 310.,  78.,  87.,  37.,  55., 135., 131.,
       206.,  55., 230., 220.,  75., 122., 179.,  66., 214., 185., 263.,
       158.,  74., 252.,  91., 104., 118., 127., 181., 116.,  66., 129.,
        87.,  84., 279., 232., 163.,  40., 118.,  53.,  91.,  99., 127.,
        78.,  61., 186., 143.,  52., 166., 136.,  97., 141., 191.,  83.,
       107., 125.,  84.,  63., 265., 156., 138., 200., 257., 148.,  25.,
        39.])

In [61]:
gnb.score(X_test,y_test)

0.0

In [64]:
from sklearn.metrics import mean_squared_error,r2_score

In [66]:
y_pred=gnb.predict(X_test)

In [67]:
r2_score(y_test,y_pred)

0.030907940793047928

In [68]:
digits=datasets.load_digits()
X=digits['data']
y=digits['target']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)
gnb=GaussianNB()

In [69]:
gnb.fit(X_train,y_train)

GaussianNB()

In [70]:
gnb.score(X_test,y_test)

0.8416666666666667

In [71]:
iris=datasets.load_iris()
X=iris['data']
y=iris['target']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)
gnb=GaussianNB()

In [72]:
gnb.fit(X_train,y_train)

GaussianNB()

In [73]:
gnb.score(X_test,y_test)

0.9333333333333333

In [ ]:
jupyter nbconvert --to PDF <notebook>.ipynb